#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if dpkg-divert --list | grep -q '/etc/pam.d/chpasswd'; then

            if [ -e /etc/pam.d/chpasswd.distrib ]; then
                rm -f /etc/pam.d/chpasswd
                mv /etc/pam.d/chpasswd.distrib /etc/pam.d/chpasswd
            fi

            dpkg-divert \
                --package eta-otp-lock \
                --remove \
                --rename \
                --divert /etc/pam.d/chpasswd.distrib \
                /etc/pam.d/chpasswd
        fi
        ;;
esac

exit 0
